<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>S3CloudCache</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <!--

├── s3cloudcache-common        # 1. 基础公共与元数据模块
├── s3cloudcache-core          # 2. 核心堆外内存与算法引擎 (核心骨架)，堆外缓冲区的实现和操作由该模块实现
├── s3cloudcache-wal           # 3. 主要实现数据的磁盘持久化和恢复，防止宕机导致堆外缓冲区数据丢失
├── s3cloudcache-storage       # 4. 云端存储适配模块 (对接 S3/MinIO)，模块提供对外API将数据上传到 云对象存储服务器
├── s3cloudcache-metadata      # 6. Core和WAL模块的元数据共享模块
└──

    -->
    <modules>
        <module>s3cloudcache-wal</module>
        <module>s3cloudcache-common</module>
        <module>s3cloudcache-core</module>
        <module>s3cloudcache-storage</module>
        <module>s3cloudcache-metadata</module>
    </modules>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.9</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.4.8</version>
            <!-- 日志实现不强制传递给使用者：由使用方自己选择 SLF4J 绑定 -->
            <scope>provided</scope>
        </dependency>
    </dependencies>


</project>
